name: CI

# env:
#   NODE_OPTIONS: --max_old_space_size=6144

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

# jobs:
#   main:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       # This enables task distribution via Nx Cloud
#       # Run this command as early as possible, before dependencies are installed
#       # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
#       # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
#       # - run: npx start-ci-run --stop-agents-after="build"

#       # Cache node_modules
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'

#       - run: npm ci --legacy-peer-deps
#       - uses: nrwl/nx-set-shas@v4

#       # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
#       # - run: npx nx-cloud record -- echo Hello World
#       # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
#       - run: npx nx affected -t lint test build

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"

      - name: 'Derive appropriate SHAs for base and head for Nx affected commands'
        uses: nrwl/nx-set-shas@v4
      
      # - name: 'Cache node_modules'
      #   uses: actions/cache@v4
      #   with:
      #     node-version:
      #     cache: 'npm'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci --legacy-peer-deps
      - run: npx nx run-many -t lint test build